rethinkdb:
  container_name: rethinkdb
  image: buddyspencer/rethinkdb:v2.4.1
  restart: always
  volumes:
      - "rethinkdb-data:/data"
  command: "rethinkdb --bind all --cache-size 2048"

adbd:
 container_name: adbd
  build: .
#  image: devicefarmer/adb:latest
  privileged: true
  ports:
    - "5037:5037"
  restart: always
  volumes:
    - "/dev/bus/usb:/dev/bus/usb"

stf:
  container_name: stf
  image: devicefarmer/stf
   links:
    - rethinkdb
    - adbd
  ports:
    - "7100:7100"
    - "7110:7110"
    - "7400-7500:7400-7500"
  environment:
    - TZ='America/Los_Angeles'
    - STF_ADMIN_EMAIL=<YOUR_EMAIL>
    - STF_ADMIN_NAME=<YOUR_NAME>
  restart: always
  command: stf local --no-screen-reset --no-cleanup --lock-rotation true --provider-min-port 7400 --provider-max-port 7500 --adb-host adbd
